roles:
  root:
    - admin
    - supervisor
    - guest
  admin:
    - supervisor
    - guest
  supervisor:
    - guest
  guest: null
test_db: 'mongodb://product:infra28@ds111441.mlab.com:11441/auth-infra-server-test'
useGoogleAuth: true
security_question: false
gmail: true
